'use strict';

//we are using jasmine's syntax for testing
describe('conFusion App E2E Testing', function(){

it('should automatically redirect to / when location hash/fragment is empty', function(){

  browser.get('index.html');
  //the absolute location of the url should match '/', since this is the first page (check state config)
  expect(browser.getLocationAbsUrl()).toMatch("/");

});

describe('index', function(){
  beforeEach(function(){
    browser.get('index.html#/');
  });

  it('should have a title', function(){
    expect(browser.getTitle()).toEqual('Ristorante Con Fusion');
  });

});

describe('menu 0 item', function(){
//navigates to the below mentioned url before executing the described tests
  beforeEach(function(){
    browser.get('index.html#/menu/0');
  });

  it('should have a name', function(){

    var name = element(by.binding('dish.name'));
    //text inside the element (which also happens to include dish.label and dish.price) which is bound to {{dish.name}} should match the below
    expect(name.getText()).toEqual('Uthapizza Hot $4.99');

  });

  it('should show the number of comments as ', function(){
    //check the total count of all the elements generated by the ng-repeater='comment in comments' to equal 5 (since we know that there are 5 comments by default)
    expect(element.all(by.repeater('comment in dish.comments')).count()).toEqual(5);

  });

  it('should show the first comment author as', function(){
    //find the element which is configured by ng-model='predicate', and type the value 'author' into that element (we know that it is an input element)
    element(by.model('predicate')).sendKeys('author');

    var author = element.all(by.repeater('comment in dish.comments')).first().element(by.binding('comment.author'));

    expect(author.getText()).toContain('25 Cent');
  });
});

describe('Feedback form', function(){

  //navigate to the contactus page
  beforeEach(function(){
    browser.get('index.html#/contactus');
  })

  it('should correctly validate e-mail addresses', function(){
    var emailElement = element(by.model('feedback.email'));
    var invalidEmailHelpBlock = element(by.id('invalidEmail'));
    var invalidEmailGlyphicon = element(by.id('invalidEmailGlyphicon'));
    var emailDiv = element(by.id('emailDiv'));
    var sendFeedbackButton = element(by.buttonText('Send Feedback'));
    var invalidEmail = 'arun@';
    var validEmail = 'akarthi2@asu.edu'
    //invalid e-mail
    emailElement.sendKeys(invalidEmail);
    //the invalid flag should be setup
    expect(emailElement.evaluate('feedbackForm.emailid.$invalid')).toBeTruthy();
    //the enter a valid-email address help-block should be shown - ngShow
    expect(invalidEmailHelpBlock.isDisplayed()).toBeTruthy();
    //the corresponding glyphicon also has to be shown - ngShow
    expect(invalidEmailGlyphicon.isDisplayed()).toBeTruthy();
    //corresponding has-error classes should also be setup
    expect(emailDiv.getAttribute('class')).toMatch(/has-error has-feedback/);
    //the Send Feedback button has to be disabled
    expect(sendFeedbackButton.getAttribute('disabled')).toBeTruthy();

    //should ask user to enter proper email address even if the text box is cleared
    emailElement.clear();
    expect(emailElement.evaluate('feedbackForm.emailid.$invalid')).toBeTruthy();
    expect(invalidEmailHelpBlock.isDisplayed()).toBeTruthy();
    expect(invalidEmailGlyphicon.isDisplayed()).toBeTruthy();
    expect(emailDiv.getAttribute('class')).toMatch(/has-error has-feedback/);

    //no errors should be displayed after proper e-mail address has been entered
    emailElement.sendKeys(validEmail);
    expect(emailElement.evaluate('feedbackForm.emailid.$invalid')).toBeFalsy();
    expect(invalidEmailHelpBlock.isDisplayed()).toBeFalsy();
    expect(invalidEmailGlyphicon.isDisplayed()).toBeFalsy();
    expect(emailDiv.getAttribute('class')).not.toMatch(/has-error has-feedback/);
  });

});

});
