'use strict';

//we are using jasmine's syntax for testing
describe('conFusion App E2E Testing', function(){

it('should automatically redirect to / when location hash/fragment is empty', function(){

  browser.get('index.html');
  //the absolute location of the url should match '/', since this is the first page (check state config)
  expect(browser.getLocationAbsUrl()).toMatch("/");

});

describe('index', function(){
  beforeEach(function(){
    browser.get('index.html#/');
  });

  it('should have a title', function(){
    expect(browser.getTitle()).toEqual('Ristorante Con Fusion');
  });

});

describe('menu 0 item', function(){
//navigates to the below mentioned url before executing the described tests
  beforeEach(function(){
    browser.get('index.html#/menu/0');
  });

  it('should have a name', function(){

    var name = element(by.binding('dish.name'));
    //text inside the element (which also happens to include dish.label and dish.price) which is bound to {{dish.name}} should match the below
    expect(name.getText()).toEqual('Uthapizza Hot $4.99');

  });

  it('should show the number of comments as ', function(){
    //check the total count of all the elements generated by the ng-repeater='comment in comments' to equal 5 (since we know that there are 5 comments by default)
    expect(element.all(by.repeater('comment in dish.comments')).count()).toEqual(5);

  });

  it('should show the first comment author as', function(){
    //find the element which is configured by ng-model='predicate', and type the value 'author' into that element (we know that it is an input element)
    element(by.model('predicate')).sendKeys('author');

    var author = element.all(by.repeater('comment in dish.comments')).first().element(by.binding('comment.author'));

    expect(author.getText()).toContain('25 Cent');
  });
});

});
